image: docker:stable

services:
  - docker:dind

stages:
  - style
  - test

style:
  image: python:3.7-alpine
  before_script:
    - apk add musl-dev gcc
    - pip install black
  stage: test
  script:
    - black --check .


test:
  before_script:
    - apk add gcc make
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
    - make first-run
    - make train
  stage: test
  script: 
    - make run-test-nlu
    - make run-test-core