image: docker:latest

services:
  - docker:dind

stages:
  - style
  - test

style:
  image: python:3.7-alpine
  stage: test
  before_script:
    - apk add musl-dev gcc
    - pip install black
  stage: test
  script:
    - black --check .


test:
  image: python:3.7-alpine
  before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext rust cargo
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install --upgrade pip
    - pip install docker-compose
    - make build
    - make train
  stage: test
  script: 
    - make run-test-nlu
    - make run-test-core
    - make test-actions