image: python:3.8-slim

stages:
  - style
  - test

style:
  stage: test
  before_script:
    - pip install black
  script:
    - black --check .


test:
  before_script:
    - apt update && apt install -y gcc make
    - pip install -r docker/requirements-development.txt
    - pip install rasa_nlu --upgrade
    - pip install rasa_core --upgrade
    - pip install rasa_core_sdk --upgrade
    - rasa train
  stage: test
  script: 
    - rasa test nlu -u test/test_data.json --model models
    - rasa test core --stories test/test_stories.md