image: python:3.7-slim-buster

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - style
  - test
  - deploy

style:
  before_script:
    - pip install black
  stage: test
  script:
    - black --check .


test:
  image: python:3.7-alpine
  before_script:
    - apt-get update
    - apt-get -y install curl jq python3-dev libffi-dev gettext cargo
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install --upgrade pip
    - pip install -r ./docker/dependencies/requirements-development.txt
    - pip install --use-deprecated=legacy-resolver --no-cache-dir -r ./docker/dependencies/x-requirements.txt
    - python3 -c "import nltk; nltk.download('stopwords');"
    - python3 -m spacy download pt_core_news_sm
    - cd bot
    - rasa train
  stage: test
  script: 
    - rasa test nlu --nlu ./data/nlu.yml --cross-validation
    - rasa test core --fail-on-prediction-errors --out results/results-core-test
    - python3 -m pytest

deploy:
    stage: deploy
    script:
        - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
        - cd core
        - bin/pencilctl build rasa -e dev --no-cache && bin/pencilctl push rasa -e dev
    only:
        refs:
            - master
