image: python:3.7-slim

stages:
  - style
  - test

style:
  stage: test
  before_script:
    - pip install black
  script:
    - black --check .


test:
  before_script:
    - apt update && apt install -y gcc make
    - make first-run
    - make train
  stage: test
  script: 
    - make run-test-nlu
    - make run-test-core