version: '3'

services:
  webchat:
    image: nginx
    volumes:
      - ./webchat/:/usr/share/nginx/html/
    ports:
      - 8001:80
  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    volumes:
      - ./bot/models/:/bot/models/
    command: "make train"

  # ================================= Bot =====================================
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
    networks:
      - bot-network
    ports:
      - 5006:5006
      - 5004:5004
      - 5005:5005
    depends_on:
      - actions
    environment:
      env_file:
        - env/auth.env
        - env/servers.env
  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    container_name: actions
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    networks:
      - bot-network
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
    command: sh -c "make actions"
    environment:
      JWT_SECRET: RRrWj+H2QEqV9O7iKBrU0zuB
      EJ_HOST: https://ejplatform.pencillabs.com.br
    env_file:
      - env/auth.env
      - env/servers.env
  # ================================= RASA X ==================================
  # Rasa X container
  x:
    container_name: x
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    networks:
      - bot-network
    volumes:
      - ./bot/:/bot/
      - /bot/tests/:/bot/tests/
    ports:
      - 5002:5002
    environment:
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - actions
    command: sh -c "make x"
    env_file:
      - env/auth.env
      - env/servers.env
  # Duckling HTTP extractor for entities such as email, date, amounts...
  duckling:
    container_name: duck
    image: "rasa/duckling"
    networks:
      - bot-network
    ports:
      - 6800:8000
    
networks: 
  bot-network:
    driver: bridge
