version: '3'

services:
  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    volumes:
      - ./bot/models/:/bot/models/
    command: "make train"

  # ================================= Bot =====================================
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
    ports:
      - 5006:5006
      - 5004:5004
      - 5005:5005
    depends_on:
      - actions

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    container_name: actions
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
    command: sh -c "make actions"

  # ================================= RASA X ==================================
  # Rasa X container
  x:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
      - /bot/tests/:/bot/tests/
    ports:
      - 5002:5002
    environment:
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - actions
    command: sh -c "make x"